---
- name: Converge
  hosts: all
  become_user: root
  become: yes

  collections:
  - tallen116.opennms

  tasks:
  - name: Debug facts
    debug:
      var: ansible_facts
  - include_role:
      name: tallen116.opennms.opennms_install
