---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos-7
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      # `network_name` is the required identifier, all other keys map to
      # arguments.
      - network_name: forwarded_port
        guest: 8980
        host: 8981
  - name: centos-8
    box: centos/8
    memory: 2048
    cpus: 2
    interfaces:
      # `network_name` is the required identifier, all other keys map to
      # arguments.
      - network_name: forwarded_port
        guest: 8980
        host: 8982
provisioner:
  name: ansible
  playbooks:
    converge: ../common/converge.yml
  log: True
verifier:
  name: ansible
