dist: bionic
language: python

env:
  global:
    - COLLECTION_NAMESPACE="tallen116"
    - COLLECTION_NAME="opennms"

services:
  - docker

jobs:
  include:
    - name: (CentOS) Install
      env:
        scenario: default_centos

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - pip install ansible-base==2.10.3
  - pip install ansible==2.10.1
  - pip install ansible-lint==4.3.7
  - pip install yamllint==1.25.0
  - pip install flake8==3.8.4
  - pip install molecule==3.0.8
  - pip install docker==4.3.1

before_script:
  # Setup collection path
  - cd ../
  - mkdir -p /home/travis/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
  #- mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  #- mv ansible-collection-$COLLECTION_NAME ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - mv ansible-collection-$COLLECTION_NAME /home/travis/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  #- cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd /home/travis/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  # Check versions
  - ansible --version
  - molecule --version
  - docker --version
  - df -h
  - pwd
  - ls -l

  - molecule test -s $scenario
