dist: bionic

language: python
python:
  - "2.7"
  - "3.6"

services:
  - docker

jobs:
  include:
    - name: (CentOS) Install
      env:
        scenario: default_centos

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - pip install ansible-base==2.10.2
  - pip install ansible==2.10.1
  - pip install ansible-lint==4.3.5
  - pip install yamllint==1.25.0
  - pip install flake8==3.8.4
  - pip install molecule==3.0.8
  - pip install docker==4.3.1

script:
  # Check versions
  - ansible --version
  - molecule --version

  - molecule test -s $scenario
