---
- name: Gather service facts
  service_facts:

- name: Verify webpage (http)
  uri:
    url: http://localhost:8980/opennms
    status_code: 200

- name: Verify webpage (https)
  uri:
    url: https://localhost:8443/opennms
    status_code: 200
    validate_certs: false

- name: Verify service
  assert:
    that:
      - ansible_facts['services']['opennms.service']['state'] == "running"
      - ansible_facts['services']['opennms.service']['status'] == "enabled"
