---

- name: Template datasources
  template:
    src: opennms-datasources.xml.j2
    dest: "{{ opennms_home }}/etc/opennms-datasources.xml"
    validate: /bin/xmllint --noout %s
    owner: root
    group: root
    mode: '0664'
  notify: opennms_restart

- name: Check if java.conf exists
  stat:
    path: "{{ opennms_home }}/etc/java.conf"
  register: java_conf_file

- name: Detect java environment
  command: "{{ opennms_home }}/bin/runjava -s"
  when:
    - not java_conf_file['stat']['exists']

- name: Import Jetty tasks
  include_tasks: opennms-jetty.yml

- name: Enable RRDTool
  template:
    src: timeseries.conf.j2
    dest: "{{ opennms_home }}/etc/opennms.properties.d/timeseries.properties"
    owner: root
    group: root
    mode: '0664'
  when: opennms_rrdtool_enable | bool
  notify: opennms_restart

- name: Enable Reverse proxy
  template:
    src: reverse_proxy.properties.j2
    dest: "{{ opennms_home }}/etc/opennms.properties.d/reverse-proxy.properties"
    owner: root
    group: root
    mode: '0664'
  when: opennms_reverse_proxy_enable
  notify: opennms_restart

- name: Set RTC client properties
  template:
    src: rtc-client.properties.j2
    dest: "{{ opennms_home }}/etc/opennms.properties.d/rtc-client.properties"
    owner: root
    group: root
    mode: '0664'
  notify: opennms_restart

- name: Set Javamail properties
  template:
    src: javamail-configuration.properties.j2
    dest: "{{ opennms_home }}/etc/javamail-configuration.properties"
    owner: root
    group: root
    mode: '0664'
  notify: opennms_restart

- name: Check if OpenNMS has been configured
  stat:
    path: "{{ opennms_home }}/etc/configured"
  register: configured_file

- name: Initialize OpenNMS
  command: "{{ opennms_home }}/bin/install -dis"
  when: not configured_file['stat']['exists']

- name: Start OpenNMS
  service:
    name: opennms
    state: started
    enabled: yes
