---

- name: Check if PostgreSQL database is initialized
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pg_version_file
  when: opennms_postgresql_install | bool

- name: Initialize PostgreSQL database
  command: "{{ postgresql_bin_dir }}/initdb -D {{ postgresql_data_dir }}"
  when:
    - not pg_version_file.stat.exists
    - opennms_postgresql_install | bool
  become: true
  become_user: postgres

- name: Start and enable PostgreSQL
  service:
    name: "{{ postgresql_service }}"
    state: started
    enabled: yes
  when: opennms_postgresql_install | bool

- name: Create OpenNMS PostgreSQL user
  community.general.postgresql_user:
    name: "{{ opennms_database_user }}"
    password: "{{ opennms_database_password }}"
    state: present

- name: Create OpenNMS PostgreSQL database
  community.general.postgresql_db:
    name: "{{ opennms_database_name }}"
    owner: "{{ opennms_database_user }}"
    encoding: UTF8
    lc_collate: en_US.utf8
    lc_ctype: en_US.utf8
    template: template0
    state: present

- name: Set password for postgres database user
  community.general.postgresql_user:
    name: "{{ opennms_database_postgres_user }}"
    password: "{{ opennms_database_postgres_password }}"
    state: present

- name: Template pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_data_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: '0600'
