---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos-7
    box: centos/7
    memory: 1024
    cpus: 1
  - name: centos-8
    box: centos/8
    memory: 1024
    cpus: 1

provisioner:
  name: ansible
  log: True
verifier:
  name: ansible
