---
# handlers file for roles/opennms_install

- name: opennms_restart
  service:
    name: opennms
    state: restarted

- name: opennms_stop
  service:
    name: opennms
    state: stopped

- name: opennms_init
  command: "{{ opennms_home }}/bin/install -dis"

- name: opennms_start
  service:
    name: opennms
    state: started

